package config

var (
	ERROR_CODE_DUPLICATE_ENTRY       string = "DUPLICATE_ENTRY"
	ERROR_CODE_INVALID_EMAIL         string = "INVALID_EMAIL"
	ERROR_CODE_INVALID_PASSWORD      string = "INVALID_PASSWORD"
	ERROR_CODE_INVALID_TOKEN         string = "INVALID_TOKEN"
	ERROR_CODE_INTERNAL_SERVER_ERROR string = "INTERNAL_SERVER_ERROR"
	ERROR_CODE_UNAUTHORIZED          string = "UNAUTHORIZED"
	ERROR_CODE_NOT_FOUND             string = "NOT_FOUND"
	ERROR_CODE_BAD_REQUEST           string = "BAD_REQUEST"
	ERROR_CODE_UNPROCESSABLE_ENTITY  string = "UNPROCESSABLE_ENTITY"
	ERROR_CODE_FORBIDDEN             string = "FORBIDDEN"
	ERROR_CODE_USER_NOT_FOUND        string = "USER_NOT_FOUND"
)
